language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "rolling_tools"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

script:
  - ./gradlew check
  - ./gradlew sonarqube
